server:
  port: 8082

spring:
  datasource:
    url: '{cipher}AQBgpKw7CZnUVQnm7vmeNnCuWi4I7HL8BmnZ63WXMtQOOGiN7aAaO/sEzyRAHbDyXvMfh+SA9WmMtTtG6WLaTZttJnUcFXvXeU9JQn6DyU5fDE4aH1JT5xzpfz+UpgZOPzSJ6vEaRnBRj0zLofegEFQTBfuj1VTlYttusSfVS+Wc+g3Z2nDZZO/QYqZKRLVMq2hfEQ1EQmE+lAjLZxR+sw8Va66Gw7t+0a2kBEDIhAvsYZvJ0ytXYA6hzU4P3eIcBYBsTSPupMX4noxlLqBDUQ8B7sOX6pD4jyypBqzjVtbYkaOSUrenhrBAfJqPkVVp8M1VDfr0GRgcgPTkbrbrGbFYtx4IbpNLZsgKQDRL7VmKJDzeBXAEOaYn7TchiHqWztQDWgfj6SvCcivWSR5w8qS3sfCwAuifqkS+0NBoUq0wh36NggWAAbPfVwrs+meYm+8='

file:
  storage:
    enabled: true
    bucketName: '{cipher}AQCG8+0RR3/N9KZFBxwvLFWGJUbl3bTeEgRji5pD6agnhccV1Ur1d2DjrFfjuFRQowRLbfYrGtiTReJhH/cDFWQ9bdwIX6/9W8QWxpb/WLl+YpfTZ4MiQ/du8fHeinAksBjnsCYQSaZFH3RwAuewWmaX6HMBMCI30qQELY8+YKwIvbDuN4XSDgVXWZUFfQs8YdsRrU4s4yYc2VmsA643uTX1hDSlItZkS3I9MjQNz0uQudYAJ1Dvu53tYaM3Bupe8rd19RBVLI1DwRpN3Klq8XaRREt+FyYiyPzGHVTFTfg5mvsAWO9MZmT/No176Ple1ZKTQvEXN5k3d/wLCxBqyBEDOkDRkzs7FcbmlSo1NhKn9WAxB/pRkuxUUed2QzFHemzGQYLamVbkMw84X1+kW6XZ'
