server:
  port: 8085

spring:
  datasource:
    url: '{cipher}QAEdfDZHtTraaaV1I4SLExqV+UPTqmvG3FGm+I2T5cXICPnYLYy5GOvaofRcfRIn/TEjxfQXelNKeCiDA7DdphHK88XrxEuVk/rFuP6kX3ZZ1tQUcRQnTyiTWlY5d5FfZyhdX+2qeKyfebbVvOHEZlfqk+J118qtEbwrEwMx+qTegR4Q5uF6GM5QJsWikXoqo7uj81Z88v3/3TKWVR309uihRNvV61jvnV3T5YtPCTcY8vRmqhKZvHi0jIUluIx+rDyjM4UOZEnblE9Vz9IPI4LL0ClkYNu6WKP9rbPZvK0ADd90+UNRCzcm/GVcmKl+9gKRLoFR8Pwnf0GZZFQHgWRuvqgWTND+oitLFDA5zPR4bM/Vcz9bo5VuHrGF0zRY5TIbB1LwZjeiu5qw9f9Oo7tIEBU5h6+QeMqShonwxTF8/DDGJp3TOp0BAKeTB561ko='

bpmn:
  ribbon:
    listOfServers: http://localhost:9999
