server:
  port: 8085

spring:
  datasource:
    url: '{cipher}AQAzSGBhvgjtQ49kTrKpcupV0QETCy3HV7jOXQKupGxesN5XIwkm3MI+2xYj6L1+oX4P/BJUcTjGZPAHiS8Oi92qCvrQMSDKy3fLodDr665FtomIcAHznW8gvmaINlyoKqj549YCbzFGPNCKtGoxG10oj3YgFtv5/K87MNq3vGVGVwWfTMGGsG6duz6ZfHdPqWu0XdxGPvhoSeLUlYJntZduzG8qUkVM5K7d5D8TOIZFyoWJ/kscMe4gj/BoHoUjb1S+gcCLIDrR3UKVnoU5AjaiRNGdqqAgSwpmW+2ThbfG3cNShinM6sVKoSpA/VrlpZYJbbLXERGPAYB2XthlNqnvu2QbtQU3Q4SW574Yz7vdkr9m42eoHTztDYa2Lle2B5kCPTictg/ua5rKdeZTipiNDXa1yNf2CwnWv8tDIz3N3AtOEfGW7iLylvQyWgyjfKE='

bpmn:
  ribbon:
    listOfServers: http://localhost:9999
