server:
  port: 8086

spring:
  datasource:
    url: '{cipher}AQCGFq2rlZYvU3gAwcXhNkhBz6dwE4wPKWy7MbKLq/2LnHhlH2/VugFW2tWm2PzqbM3PY+bI90lTVPdWGD1NKJxODa6aQ6dzX9fsInJaegJLI9qcdg+HPnBA4ZITAGHTkIMzZej+cOpkcuo396N0kSq5eF1uwByphCEDJ+8w+2+yz2GxXQh+0o/jX+X+swLm+XEtXs6ABH3g9iPwhbs8KptQ4Hq9O3ijnKUkxmc8q6oDnqgGoZRV+AcgTWH72TysuKM+pX/4ty4+nejux7XuzgPj38PwSu01PoNDd9zKpysrcNL2UZDi3W/tLnBAWbHK+I0oeyuG64f4jlwuqXM04ZaXJ3/T8brDpsUY3ZevGgjVozRHnOIS0cXUNy49AzzK9XJup4QOnOCzLCihV6LfsScCFRUvIrsevZrUVCjJfH8KVuGzbKGmzXLYjwMM2tha0SQ='

bpmn:
  ribbon:
    listOfServers: http://localhost:9999
