server:
  port: 8081

spring:
  datasource:
    url: '{cipher}AQCDPbEOmrVKZHGYL6vXkDE5ezb1LpfnI/Sc7hVNtjsTyDyr8CtF2OtSUaz/i4xNyQQ83UMalbtZlsr4aWHPGbH3zB7SE9dIhmGZovuisjDnAXeWL1YikYwYimApIhSFJ5Vqtpi/gVamH12LfvyzKsNfBXjv/+kVXfCYCAdIb0rnYE805P/vYySPXg+EwKRb8ZFiQGw2yF9Mdv7kHjrk9IuIyeeugbrPEvnmyRqSo1JQM4Z5nFhoqZVfv4CmSm6Hx/v2uHVO0lpiJRaBLsKHkd7apjnZiP9BVuxPgT3DYqmzJ7a3JUaFczDLdRer4/+NlqWRfgWQKFMngHBdI9ocbwnzZCXjYVrpVwLg4pNuiS41fz/k1aH8CxJTqy/KT+giyVsNZ3ybw0xqQB1SKkUfNpl4QYZBfTH5dUuv8pBGVUQYNPu9SrbfNgEVs4RDkDurHTo='

user:
  register:
    enabled: true
  password:
    random-password-length: 6
    reset-code:
      validity: 86400
      length: 32
      header: FORGOT PASSWORD
      template: USER_PASSWORD_RETRIEVE_TEMPLATE
    update:
      mail:
        enabled: true
        header: PASSWORD UPDATE
        template: USER_PASSWORD_MAIL_TEMPLATE
      sms:
        enabled: false
        template: USER_PASSWORD_SMS_TEMPLATE
    reset:
      mail:
        enabled: true
        header: PASSWORD RESET
        template: USER_PASSWORD_RESET_MAIL_TEMPLATE
      sms:
        enabled: false
        template: USER_PASSWORD_RESET_SMS_TEMPLATE
  exception:
    empty-password: Password should not be empty when mail activation is disabled
  activation:
    mail:
      enabled: true
      token-length: 32
      header: EMAIL ACTIVATION
      template: ACTIVATION_MAIL_TEMPLATE
    sms:
      enabled: false
      token-length: 4
      template: ACTIVATION_SMS_TEMPLATE


cms:
  ribbon:
    listOfServers: http://localhost:8082

notification:
  ribbon:
    listOfServers: http://localhost:8003

bpmn:
  ribbon:
    listOfServers: http://localhost:9999
