server:
  port: 8084

spring:
  datasource:
    url: '{cipher}AQCVzyPgVPUSWYsqpCze8IQZF7qFkFXOzkSvJSAOI/otqixLd4TgO7BpFzBCmsLdOPFY8TMpU6uO9UjjVWWQWoA4sgFcZTPhXtyf9y8V6sXJYmdPk8HPPq3BYJCvz9l7z07918X6gGFL0MVErQpboIp+WgOkVDHY2TRsFUNTIeq/tu2tEi0nHaP3jjyxNYspe46a/Wd0yMsvdz9i1zLark5LyVmPLKe+2C7BSaD77RsQL3SUuvBLkWSxcdMfBgi/4OCQ8aWJARrh4iaDAFpPcnYl7Ggt1rkq5fs8mWWXKJFk9rDRvNLc9PeHIY9ifLBSpaRExDj88JYcBQtVQAB/raAQ+C0aS28Px00N2q4W+ytbYiFcV49Qq0S+vxW4jA7/PpwogoDR/BvasCg0rETrFeYm0V1Vgm8bVGbZMHbUBQepnjlYllutjXnE7tx2s0D47Es='

bpmn:
  ribbon:
    listOfServers: http://localhost:9999
